name: Release to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # e.g., v1.0.0
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set version in pom.xml
        run: mvn versions:set -DnewVersion=${VERSION#v} -DgenerateBackupPoms=false

      - name: Commit updated pom.xml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Update version to ${VERSION#v}"
          git push

      - name: Copy Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cp .github/maven/settings.xml ~/.m2/settings.xml

      - name: Inject GitHub credentials
        run: |
          sed -i "s|<username>.*</username>|<username>sten-vw</username>|" ~/.m2/settings.xml
          sed -i "s|<password>.*</password>|<password>${{ secrets.GH_PAT }}</password>|" ~/.m2/settings.xml

      - name: Deploy to GitHub Packages
        run: mvn deploy -DskipTests -DdryRun=true
