name: Release to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # e.g., v1.0.0
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: prerelease
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set version in pom.xml
        run: mvn versions:set -DnewVersion=${VERSION#v} -DgenerateBackupPoms=false

      - name: Commit updated pom.xml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Update version to ${VERSION#v}"
          git push
          
      - name: Move tag to latest commit
        run: |
          git tag -d ${VERSION}
          git push origin :refs/tags/${VERSION}
          git tag ${VERSION}
          git push origin ${VERSION}

      - name: Copy Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cp .github/maven/settings.xml ~/.m2/settings.xml

      - name: Inject GitHub credentials
        run: |
          sed -i "s|<username>.*</username>|<username>${{ github.actor }}</username>|" ~/.m2/settings.xml
          sed -i "s|<password>.*</password>|<password>${{ secrets.GITHUB_TOKEN }}</password>|" ~/.m2/settings.xml

      - name: Deploy to GitHub Packages
        run: mvn deploy -DskipTests
